import type { APIRoute } from 'astro';
import { Resend } from 'resend';

// Simple in-memory rate limiting
const rateLimitMap = new Map<string, { count: number; resetTime: number }>();
const RATE_LIMIT = 5; // max requests
const RATE_WINDOW = 600000; // 10 minutes in ms

function isRateLimited(ip: string): boolean {
  const now = Date.now();
    const entry = rateLimitMap.get(ip);
      if (!entry || now > entry.resetTime) {
          rateLimitMap.set(ip, { count: 1, resetTime: now + RATE_WINDOW });
              return false;
                }
                  entry.count++;
                    return entry.count > RATE_LIMIT;
                    }

                    function escapeHtml(str: string): string {
                      return str
                          .replace(/&/g, '&amp;')
                              .replace(/</g, '&lt;')
                                  .replace(/>/g, '&gt;')
                                      .replace(/"/g, '&quot;')
                                          .replace(/'/g, '&#039;');
                                          }

                                          function isValidEmail(email: string): boolean {
                                            return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) && email.length <= 254;
                                            }

                                            export const POST: APIRoute = async ({ request }) => {
                                              try {
                                                  // Rate limiting
                                                      const ip = request.headers.get('x-forwarded-for') || request.headers.get('x-real-ip') || 'unknown';
                                                          if (isRateLimited(ip)) {
                                                                return new Response(JSON.stringify({ success: false, message: 'Trop de demandes. Veuillez réessayer dans quelques minutes.' }), {
                                                                        status: 429, headers: { 'Content-Type': 'application/json' }
                                                                              });
                                                                                  }

                                                                                      // Block suspicious user agents
                                                                                          const ua = request.headers.get('user-agent') || '';
                                                                                              if (!ua || /bot|crawl|spider|curl|wget|python|scrapy/i.test(ua)) {
                                                                                                    return new Response(JSON.stringify({ success: false, message: 'Requête non autorisée.' }), {
                                                                                                            status: 403, headers: { 'Content-Type': 'application/json' }
                                                                                                                  });
                                                                                                                      }

                                                                                                                          const body = await request.json();
                                                                                                                              const { name, email, phone, message, consent, copy, website } = body;

                                                                                                                                  // Honeypot check
                                                                                                                                      if (website) {
                                                                                                                                            return new Response(JSON.stringify({ success: true, message: 'Message envoyé.' }), {
                                                                                                                                                    status: 200, headers: { 'Content-Type': 'application/json' }
                                                                                                                                                          });
                                                                                                                                                              }

                                                                                                                                                                  // Validation
                                                                                                                                                                      if (!name || !email || !message || !consent) {
                                                                                                                                                                            return new Response(JSON.stringify({ success: false, message: 'Veuillez remplir tous les champs obligatoires.' }), {
                                                                                                                                                                                    status: 400, headers: { 'Content-Type': 'application/json' }
                                                                                                                                                                                          });
                                                                                                                                                                                              }

                                                                                                                                                                                                  if (typeof name !== 'string' || name.length > 100) {
                                                                                                                                                                                                        return new Response(JSON.stringify({ success: false, message: 'Nom invalide.' }), {
                                                                                                                                                                                                                status: 400, headers: { 'Content-Type': 'application/json' }
                                                                                                                                                                                                                      });
                                                                                                                                                                                                                          }

                                                                                                                                                                                                                              if (!isValidEmail(email)) {
                                                                                                                                                                                                                                    return new Response(JSON.stringify({ success: false, message: 'Email invalide.' }), {
                                                                                                                                                                                                                                            status: 400, headers: { 'Content-Type': 'application/json' }
                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                          if (typeof message !== 'string' || message.length > 2000) {
                                                                                                                                                                                                                                                                return new Response(JSON.stringify({ success: false, message: 'Message trop long (2000 caractères max).' }), {
                                                                                                                                                                                                                                                                        status: 400, headers: { 'Content-Type': 'application/json' }
                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                      if (phone && (typeof phone !== 'string' || phone.length > 20)) {
                                                                                                                                                                                                                                                                                            return new Response(JSON.stringify({ success: false, message: 'Téléphone invalide.' }), {
                                                                                                                                                                                                                                                                                                    status: 400, headers: { 'Content-Type': 'application/json' }
                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                  // Sanitize
                                                                                                                                                                                                                                                                                                                      const safeName = escapeHtml(name.trim());
                                                                                                                                                                                                                                                                                                                          const safeEmail = escapeHtml(email.trim());
                                                                                                                                                                                                                                                                                                                              const safePhone = phone ? escapeHtml(phone.trim()) : 'Non renseigné';
                                                                                                                                                                                                                                                                                                                                  const safeMessage = escapeHtml(message.trim());

                                                                                                                                                                                                                                                                                                                                      // Send email via Resend
                                                                                                                                                                                                                                                                                                                                          const resendApiKey = import.meta.env.RESEND_API_KEY;
                                                                                                                                                                                                                                                                                                                                              if (!resendApiKey) {
                                                                                                                                                                                                                                                                                                                                                    console.error('RESEND_API_KEY is not configured');
                                                                                                                                                                                                                                                                                                                                                          return new Response(JSON.stringify({ success: false, message: 'Erreur de configuration serveur.' }), {
                                                                                                                                                                                                                                                                                                                                                                  status: 500, headers: { 'Content-Type': 'application/json' }
                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                const resend = new Resend(resendApiKey);
                                                                                                                                                                                                                                                                                                                                                                                    const recipientEmail = import.meta.env.CONTACT_EMAIL || 'zhuit.pro@gmail.com';

                                                                                                                                                                                                                                                                                                                                                                                        // Send notification to Amélie
                                                                                                                                                                                                                                                                                                                                                                                            await resend.emails.send({
                                                                                                                                                                                                                                                                                                                                                                                                  from: 'Site Amélie Gothier <onboarding@resend.dev>',
                                                                                                                                                                                                                                                                                                                                                                                                        to: [recipientEmail],
                                                                                                                                                                                                                                                                                                                                                                                                              subject: `Nouveau message de ${safeName}`,
                                                                                                                                                                                                                                                                                                                                                                                                                    html: `
                                                                                                                                                                                                                                                                                                                                                                                                                            <h2>Nouveau message depuis le site</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <p><strong>Nom :</strong> ${safeName}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <p><strong>Email :</strong> ${safeEmail}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p><strong>Téléphone :</strong> ${safePhone}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <hr />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p><strong>Message :</strong></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>${safeMessage.replace(/\n/g, '<br />')}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <hr />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p style="color: #888; font-size: 0.85em;">Ce message a été envoyé depuis le formulaire de contact du site amelie-gothier-naturopathe.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Send copy to prospect if requested
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (copy) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await resend.emails.send({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            from: 'Amélie Gothier Naturopathe <onboarding@resend.dev>',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    to: [email.trim()],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            subject: 'Copie de votre message - Amélie Gothier Naturopathe',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    html: `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2>Copie de votre message</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Bonjour ${safeName},</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>Voici une copie du message que vous avez envoyé :</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <blockquote style="border-left: 3px solid #6c9a4e; padding-left: 1rem; color: #555;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ${safeMessage.replace(/\n/g, '<br />')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </blockquote>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>Je reviendrai vers vous dans les meilleurs délais.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>Amélie Gothier — Naturopathe à Bordeaux</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return new Response(JSON.stringify({ success: true }), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  status: 200, headers: { 'Content-Type': 'application/json' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('Contact form error:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return new Response(JSON.stringify({ success: false, message: 'Une erreur est survenue. Veuillez réessayer.' }), {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      status: 500, headers: { 'Content-Type': 'application/json' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };